#!/usr/bin/env python3
"""
AI Audit Evaluation Agents — Reference Implementation (stateless)
==================================================================

Single-file, runnable implementation of the multi-agent system described in
"AI Audit Evaluation Agents — Python Multi-Agent Implementation Guide
(Azure OpenAI)".

This version is fully stateless: nothing is persisted anywhere. Every audit
check is computed on the fly from the FastAPI request payload and returned
directly in the response. There is no database, no file-based store, and no
server-side session state — call POST /audit/evaluate with an EvidenceBundle
and get an AuditRunReport back in the same request/response cycle.

What this file implements (guide section references in brackets):

  - Core data contracts: EvidenceBundle, AgentVerdict, AuditRunReport   [Sec 5]
  - Requirement-to-agent routing config, loaded from YAML if present,
    else falls back to the embedded routing table                     [Sec 2, 4.3]
  - Ingestion/normalization helpers for text docs                      [Phase 3]
  - A common Connector interface + Jira / GitLab / Datadog / Doc-store /
    IAM connectors (each degrades to a clearly-labeled mock/manual
    response if no credentials are configured, per the guide's
    "connector-failure -> Partial, never fabricate a Y" rule)          [Phase 4]
  - Azure OpenAI wrapper with JSON-mode structured output and schema
    validation + one retry. Falls back to a deterministic offline stub
    if no Azure OpenAI credentials are configured, so this file runs
    end-to-end with zero external deps.                                [Phase 5]
  - BaseAgent + 5 concrete agents (Log Evidence, Document,
    Compliance Registry, Jira/GitLab, Access)                          [Phase 6]
  - Orchestrator: config-driven routing + concurrent fan-out           [Phase 7]
  - Guardrails: citation grounding, schema/range validation,
    confidence gating, content-safety hook                             [Phase 8]
  - Aggregator: builds the AuditRunReport from the in-memory results,
    no storage involved                                                [Phase 9]
  - A stateless review/override transform endpoint (Phase 10's
    decision logic without a persisted audit trail — see note below)
  - FastAPI app exposing /health, /audit/evaluate, /audit/review
  - A CLI offline demo mode (`python ai_audit_agents.py demo`) that
    exercises the entire pipeline with mocked connectors and the
    offline LLM stub — no Azure/Jira/GitLab/Datadog credentials needed.

Note on persistence
--------------------
The guide's Phase 2 (persistence layer) and the audit-trail requirement
behind Requirement #1/#10 assume verdicts, LLM calls, and human overrides
are durably stored so an auditor can reconstruct "who submitted what, when,
and what the model said" after the fact. This version deliberately has none
of that: it is a pure request-in/response-out evaluator. If/when you need
an audit trail again, the natural seam is the `on_verdict` callback hook
threaded through `route_and_evaluate()` — wire it to whatever store you
choose (Postgres, Cosmos DB, a message queue, etc.) without touching the
agents, connectors, or orchestration logic.

Phases 11-13 (test suite/CI, security review, deployment/kill-switch
infra) are process and infrastructure concerns, not application code;
see the accompanying project scaffold (create_project.sh) for where
they land (tests/, infra/, .env.example).

Usage
-----
    python ai_audit_agents.py demo            # offline, no external services
    python ai_audit_agents.py serve           # run the FastAPI app (uvicorn)
    uvicorn ai_audit_agents:app --reload      # equivalent, dev-style

Configuration is via environment variables (see .env.example generated by
create_project.sh). Every external integration is optional: anything not
configured degrades to a mock/manual connector or the offline LLM stub
rather than crashing, so the system is always runnable.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import re
import sys
import time
import uuid
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Awaitable, Callable, Optional

from pydantic import BaseModel, Field, ValidationError, field_validator

# ---------------------------------------------------------------------------
# Optional dependencies — the file must still import and run without these.
# ---------------------------------------------------------------------------
try:
    import httpx
except ImportError:  # pragma: no cover
    httpx = None  # type: ignore

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None  # type: ignore

try:
    from openai import AsyncAzureOpenAI
except ImportError:  # pragma: no cover
    AsyncAzureOpenAI = None  # type: ignore

try:
    from docx import Document as DocxDocument  # python-docx
except ImportError:  # pragma: no cover
    DocxDocument = None  # type: ignore

try:
    from pypdf import PdfReader
except ImportError:  # pragma: no cover
    PdfReader = None  # type: ignore

try:
    from fastapi import FastAPI, HTTPException
except ImportError:  # pragma: no cover
    FastAPI = None  # type: ignore
    HTTPException = None  # type: ignore

logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
log = logging.getLogger("ai_audit_agents")


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ===========================================================================
# Section 5 — Core Data Contracts
# ===========================================================================

class ComplianceStatus(str, Enum):
    YES = "Y"
    NO = "N"
    PARTIAL = "Partial"
    NOT_APPLICABLE = "N/A"


class EvidenceBundle(BaseModel):
    """Normalized payload the UI sends for one requirement or one run."""

    session_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    requirement_ids: list[int]
    user_input: Optional[str] = None
    document_refs: list[str] = Field(default_factory=list)
    screenshot_refs: list[str] = Field(default_factory=list)
    jira_link: Optional[str] = None
    gitlab_link: Optional[str] = None
    datadog_link: Optional[str] = None
    submitted_by: str = "unknown"
    submitted_at: datetime = Field(default_factory=utcnow)

    @field_validator("requirement_ids")
    @classmethod
    def _non_empty(cls, v: list[int]) -> list[int]:
        if not v:
            raise ValueError("requirement_ids must contain at least one id")
        return v


class AgentVerdict(BaseModel):
    """What every specialized agent returns — schema-enforced."""

    requirement_id: int
    agent_name: str
    compliance_status: ComplianceStatus
    rationale: str
    evidence_citations: list[str] = Field(default_factory=list)
    gaps: list[str] = Field(default_factory=list)
    confidence: float = Field(ge=0, le=1)
    model_name: str
    prompt_version: str
    flagged_for_human_review: bool = False
    evaluated_at: datetime = Field(default_factory=utcnow)


class AuditRunReport(BaseModel):
    session_id: str
    verdicts: list[AgentVerdict]
    overall_readiness_pct: float
    flagged_for_human_review: list[int]
    generated_at: datetime = Field(default_factory=utcnow)


class ReviewAction(str, Enum):
    APPROVE = "approve"
    OVERRIDE = "override"


class ReviewRequest(BaseModel):
    """Stateless review/override transform: the caller sends the verdict
    it received from /audit/evaluate back along with the reviewer's
    decision, and gets the updated verdict back. Nothing is stored here —
    persisting the resulting verdict (and who reviewed it) is the caller's
    responsibility if/when an audit trail is needed again."""

    verdict: AgentVerdict
    reviewer: str
    action: ReviewAction
    rationale: str
    override_status: Optional[ComplianceStatus] = None


# ===========================================================================
# Section 2 / 4.3 — Requirement-to-agent routing config (config-as-data)
# ===========================================================================

# Embedded fallback for the routing table in Section 2 of the guide.
# A real deployment overrides this by dropping a config/requirements.yaml
# next to this file (see load_requirements_config()) so audit changes do
# not require redeploying code.
DEFAULT_REQUIREMENTS_CONFIG: list[dict[str, Any]] = [
    {"id": 1, "category": "Audit Logging", "agent": "log_evidence",
     "text": "Provide sample audit-log entry proving logs capture inputs, "
             "outputs, prompts, timestamps, session metadata, model info, sources.",
     "automatable": "Y"},
    {"id": 2, "category": "Validation Controls", "agent": "document",
     "text": "Document each validation control (UI, format, middleware, "
             "identifier-existence) and where it lives.",
     "automatable": "Partial"},
    {"id": 3, "category": "Output Validation", "agent": "document",
     "text": "Evidence of output-validation controls: template adherence, "
             "completeness, accuracy, exception handling.",
     "automatable": "Partial"},
    {"id": 4, "category": "Compliance Approvals", "agent": "compliance_registry",
     "text": "PRISM / AI Governance / BCIQ / ISS approval artifacts.",
     "automatable": "Y"},
    {"id": 5, "category": "Design Documentation", "agent": "document",
     "text": "AI Use Case Whitepaper, Confluence docs, SD3/TDD.",
     "automatable": "Y"},
    {"id": 6, "category": "SDLC & Change Mgmt", "agent": "jira_gitlab",
     "text": "All Jira projects/stories + ClearPath IDs related to the use case.",
     "automatable": "Y"},
    {"id": 7, "category": "User Feedback", "agent": "jira_gitlab",
     "text": "Pilot feedback that led to an enhancement/config/prompt change.",
     "automatable": "Y"},
    {"id": 8, "category": "AI Guardrails", "agent": "document",
     "text": "Decision record for guardrail tooling (e.g., Lumenova) applicability.",
     "automatable": "Partial"},
    {"id": 9, "category": "Kill-Switch / Rollback", "agent": "jira_gitlab",
     "text": "Kill-switch implementation & test evidence, before/after config.",
     "automatable": "Y"},
    {"id": 10, "category": "Human-in-the-Loop", "agent": "document",
     "text": "User guidance/training describing review responsibilities.",
     "automatable": "Y"},
    {"id": 11, "category": "Access Mgmt — EU Users", "agent": "access",
     "text": "Confirm whether EU-based users use the system.",
     "automatable": "Y"},
    {"id": 12, "category": "Access Mgmt — Service Accounts", "agent": "access",
     "text": "Confirm existence of non-human/service accounts.",
     "automatable": "Y"},
    {"id": 13, "category": "Access Mgmt — Account Review", "agent": "access",
     "text": "Owner + review process for any service accounts.",
     "automatable": "Y"},
]


def load_requirements_config() -> dict[int, dict[str, Any]]:
    """Load routing config from config/requirements.yaml if present,
    else fall back to the embedded table. Returns {req_id: entry}."""
    cfg_path = Path(os.getenv("REQUIREMENTS_CONFIG_PATH", "config/requirements.yaml"))
    entries = DEFAULT_REQUIREMENTS_CONFIG
    if cfg_path.exists() and yaml is not None:
        try:
            with cfg_path.open() as f:
                loaded = yaml.safe_load(f)
            if loaded:
                entries = loaded
                log.info("Loaded requirement routing config from %s", cfg_path)
        except Exception as exc:  # pragma: no cover
            log.warning("Failed to load %s (%s); using embedded defaults", cfg_path, exc)
    return {e["id"]: e for e in entries}


REQUIREMENTS: dict[int, dict[str, Any]] = load_requirements_config()


# ===========================================================================
# Phase 3 — Ingestion / normalization helpers
# ===========================================================================

def extract_text_from_ref(ref: str) -> str:
    """Best-effort text extraction for a document reference.

    Accepts a filesystem path (.txt/.md/.docx/.pdf) and extracts text with
    the appropriate library when available; any other string (URL, or a
    raw text snippet passed directly for demo/testing) is returned as-is.
    """
    path = Path(ref)
    try:
        if path.suffix.lower() in (".txt", ".md") and path.exists():
            return path.read_text(errors="ignore")
        if path.suffix.lower() == ".docx" and path.exists() and DocxDocument is not None:
            doc = DocxDocument(str(path))
            return "\n".join(p.text for p in doc.paragraphs)
        if path.suffix.lower() == ".pdf" and path.exists() and PdfReader is not None:
            reader = PdfReader(str(path))
            return "\n".join((p.extract_text() or "") for p in reader.pages)
    except Exception as exc:  # pragma: no cover
        log.warning("Failed to extract text from %s: %s", ref, exc)
        return f"[extraction failed for {ref}: {exc}]"
    # Not a recognized/existing file — treat as inline text or an opaque link.
    return ref


def validate_link(url: Optional[str]) -> bool:
    """Cheap well-formedness check; a real deployment also does a HEAD
    request per Phase 3 ('reject/flag broken links immediately')."""
    if not url:
        return False
    return bool(re.match(r"^https?://", url.strip()))


# ===========================================================================
# Phase 4 — Connector layer (tools)
# ===========================================================================

class ConnectorResult(BaseModel):
    source: str
    ref: Optional[str] = None
    ok: bool
    content: str
    citation: Optional[str] = None
    error: Optional[str] = None


class Connector(ABC):
    name: str

    @abstractmethod
    async def fetch(self, ref: Optional[str]) -> ConnectorResult:
        """Fetch and normalize evidence for `ref`. Must never raise —
        connector failures degrade to ConnectorResult(ok=False, ...) so
        agents can turn that into a 'Partial — evidence unavailable'
        verdict instead of crashing or fabricating a 'Y' (guardrail #9.1)."""


async def _http_get(url: str, headers: dict[str, str], timeout: float = 10.0):
    if httpx is None:
        raise RuntimeError("httpx not installed")
    async with httpx.AsyncClient(timeout=timeout) as client:
        resp = await client.get(url, headers=headers)
        resp.raise_for_status()
        return resp


class JiraConnector(Connector):
    name = "jira"

    def __init__(self):
        self.base_url = os.getenv("JIRA_BASE_URL", "").rstrip("/")
        self.token = os.getenv("JIRA_API_TOKEN", "")
        self.email = os.getenv("JIRA_EMAIL", "")

    @staticmethod
    def _extract_key(ref: str) -> Optional[str]:
        m = re.search(r"([A-Z][A-Z0-9]+-\d+)", ref)
        return m.group(1) if m else None

    async def fetch(self, ref: Optional[str]) -> ConnectorResult:
        if not ref or not validate_link(ref):
            return ConnectorResult(source=self.name, ref=ref, ok=False, content="",
                                    error="No/invalid Jira link supplied")
        issue_key = self._extract_key(ref)
        if not (self.base_url and self.token and httpx is not None):
            return ConnectorResult(
                source=self.name, ref=ref, ok=True,
                content=f"[MOCK Jira evidence] Issue {issue_key or ref}: status=Done, "
                        f"summary='Implement feature per requirement', "
                        f"comments=2, changelog shows transitions To Do -> In Progress -> Done. "
                        f"(Configure JIRA_BASE_URL/JIRA_API_TOKEN for live data.)",
                citation=f"jira:{issue_key or ref}",
            )
        try:
            resp = await _http_get(
                f"{self.base_url}/rest/api/3/issue/{issue_key}",
                headers={"Authorization": f"Bearer {self.token}", "Accept": "application/json"},
            )
            data = resp.json()
            fields = data.get("fields", {})
            content = (
                f"Jira {issue_key}: status={fields.get('status', {}).get('name')}, "
                f"summary={fields.get('summary')}, "
                f"updated={fields.get('updated')}"
            )
            return ConnectorResult(source=self.name, ref=ref, ok=True, content=content,
                                    citation=f"jira:{issue_key}")
        except Exception as exc:
            return ConnectorResult(source=self.name, ref=ref, ok=False, content="",
                                    error=f"Jira fetch failed: {exc}")


class GitLabConnector(Connector):
    name = "gitlab"

    def __init__(self):
        self.base_url = os.getenv("GITLAB_BASE_URL", "").rstrip("/")
        self.token = os.getenv("GITLAB_API_TOKEN", "")

    @staticmethod
    def _extract_project_and_ref(url: str) -> tuple[Optional[str], Optional[str]]:
        m = re.search(r"/-/(?:merge_requests|commit)/([\w]+)", url)
        proj = re.search(r"gitlab\.[^/]+/([\w./-]+?)/-/", url)
        return (proj.group(1) if proj else None, m.group(1) if m else None)

    async def fetch(self, ref: Optional[str]) -> ConnectorResult:
        if not ref or not validate_link(ref):
            return ConnectorResult(source=self.name, ref=ref, ok=False, content="",
                                    error="No/invalid GitLab link supplied")
        project, mr_or_commit = self._extract_project_and_ref(ref)
        if not (self.base_url and self.token and httpx is not None):
            return ConnectorResult(
                source=self.name, ref=ref, ok=True,
                content=f"[MOCK GitLab evidence] {project or ref}: MR/commit "
                        f"{mr_or_commit or 'n/a'} merged to main, CI pipeline passed, "
                        f"config diff shows kill-switch flag added. "
                        f"(Configure GITLAB_BASE_URL/GITLAB_API_TOKEN for live data.)",
                citation=f"gitlab:{project or ref}:{mr_or_commit or ''}",
            )
        try:
            proj_enc = (project or "").replace("/", "%2F")
            resp = await _http_get(
                f"{self.base_url}/api/v4/projects/{proj_enc}/repository/commits/{mr_or_commit}",
                headers={"PRIVATE-TOKEN": self.token},
            )
            data = resp.json()
            content = f"GitLab commit {mr_or_commit}: title={data.get('title')}, status={data.get('status')}"
            return ConnectorResult(source=self.name, ref=ref, ok=True, content=content,
                                    citation=f"gitlab:{project}:{mr_or_commit}")
        except Exception as exc:
            return ConnectorResult(source=self.name, ref=ref, ok=False, content="",
                                    error=f"GitLab fetch failed: {exc}")


class DatadogConnector(Connector):
    name = "datadog"

    def __init__(self):
        self.api_key = os.getenv("DATADOG_API_KEY", "")
        self.app_key = os.getenv("DATADOG_APP_KEY", "")
        self.site = os.getenv("DATADOG_SITE", "datadoghq.com")

    async def fetch(self, ref: Optional[str]) -> ConnectorResult:
        if not ref or not validate_link(ref):
            return ConnectorResult(source=self.name, ref=ref, ok=False, content="",
                                    error="No/invalid Datadog link supplied")
        if not (self.api_key and self.app_key and httpx is not None):
            return ConnectorResult(
                source=self.name, ref=ref, ok=True,
                content=(
                    "[MOCK Datadog evidence] Sample log entry: "
                    '{"timestamp":"2025-01-01T00:00:00Z","session_id":"sess-123",'
                    '"model":"gpt-4o","prompt":"...","response":"...",'
                    '"source_refs":["doc-42"]} '
                    "(Configure DATADOG_API_KEY/DATADOG_APP_KEY for live data.)"
                ),
                citation=f"datadog:{ref}",
            )
        try:
            resp = await _http_get(
                f"https://api.{self.site}/api/v2/logs/events?filter[query]=*&page[limit]=5",
                headers={"DD-API-KEY": self.api_key, "DD-APPLICATION-KEY": self.app_key},
            )
            data = resp.json()
            content = f"Datadog sample logs: {json.dumps(data.get('data', []))[:800]}"
            return ConnectorResult(source=self.name, ref=ref, ok=True, content=content,
                                    citation=f"datadog:{ref}")
        except Exception as exc:
            return ConnectorResult(source=self.name, ref=ref, ok=False, content="",
                                    error=f"Datadog fetch failed: {exc}")


class DocStoreConnector(Connector):
    """Fetches Confluence pages by link if configured, else operates on
    uploaded document text via extract_text_from_ref (Phase 3/4)."""

    name = "doc_store"

    def __init__(self):
        self.confluence_base = os.getenv("CONFLUENCE_BASE_URL", "")
        self.token = os.getenv("CONFLUENCE_API_TOKEN", "")

    async def fetch(self, ref: Optional[str]) -> ConnectorResult:
        if not ref:
            return ConnectorResult(source=self.name, ref=ref, ok=False, content="",
                                    error="No document/Confluence reference supplied")
        if validate_link(ref) and "confluence" in ref.lower():
            if not (self.confluence_base and self.token and httpx is not None):
                return ConnectorResult(
                    source=self.name, ref=ref, ok=True,
                    content=f"[MOCK Confluence evidence] Page at {ref}: contains design "
                            f"rationale, whitepaper sections 1-4. "
                            f"(Configure CONFLUENCE_BASE_URL/CONFLUENCE_API_TOKEN for live data.)",
                    citation=f"confluence:{ref}",
                )
            try:
                resp = await _http_get(ref, headers={"Authorization": f"Bearer {self.token}"})
                return ConnectorResult(source=self.name, ref=ref, ok=True,
                                        content=resp.text[:4000], citation=f"confluence:{ref}")
            except Exception as exc:
                return ConnectorResult(source=self.name, ref=ref, ok=False, content="",
                                        error=f"Confluence fetch failed: {exc}")
        # Otherwise treat as an uploaded document reference / inline text.
        text = extract_text_from_ref(ref)
        return ConnectorResult(source=self.name, ref=ref, ok=bool(text), content=text,
                                citation=f"doc:{ref}")


class IAMConnector(Connector):
    """Per the guide: if no IAM API exists yet, this is a manual-input
    adapter that still conforms to the Connector interface, so agents
    don't need special-casing once a real IAM API is wired in later."""

    name = "iam"

    def __init__(self):
        self.api_base = os.getenv("IAM_API_BASE_URL", "")
        self.token = os.getenv("IAM_API_TOKEN", "")

    async def fetch(self, ref: Optional[str]) -> ConnectorResult:
        if self.api_base and self.token and httpx is not None:
            try:
                resp = await _http_get(f"{self.api_base}/query?q={ref or ''}",
                                        headers={"Authorization": f"Bearer {self.token}"})
                return ConnectorResult(source=self.name, ref=ref, ok=True,
                                        content=resp.text[:2000], citation="iam:live-query")
            except Exception as exc:
                return ConnectorResult(source=self.name, ref=ref, ok=False, content="",
                                        error=f"IAM fetch failed: {exc}")
        # Manual-input adapter: the submitter's free-text answer *is* the evidence.
        content = ref or "[No IAM API configured and no user_input supplied]"
        return ConnectorResult(source=self.name, ref=ref, ok=bool(ref), content=content,
                                citation="iam:manual-input")


CONNECTORS: dict[str, Connector] = {
    "jira": JiraConnector(),
    "gitlab": GitLabConnector(),
    "datadog": DatadogConnector(),
    "doc_store": DocStoreConnector(),
    "iam": IAMConnector(),
}


# ===========================================================================
# Phase 8 (partial) — Content safety hook
# ===========================================================================

def content_safety_scan(text: str) -> bool:
    """Stub integration point for Azure AI Content Safety. Returns True if
    the text is safe to store/display. Wire in the real API call here;
    kept as a pass-through so the reference implementation has no hard
    dependency on that service."""
    return True


# ===========================================================================
# Phase 5 — Azure OpenAI client wrapper
# ===========================================================================

class AzureOpenAIWrapper:
    """Centralizes all LLM calls: logging (to stdout/logger only — nothing
    is persisted), retries, schema enforcement.

    Falls back to a deterministic offline stub when Azure OpenAI is not
    configured, so `evaluate()` always returns a schema-valid AgentVerdict
    and the whole system is runnable without live credentials.
    """

    def __init__(self):
        self.endpoint = os.getenv("AZURE_OPENAI_ENDPOINT", "")
        self.api_key = os.getenv("AZURE_OPENAI_API_KEY", "")
        self.api_version = os.getenv("AZURE_OPENAI_API_VERSION", "2024-06-01")
        self.deployment = os.getenv("AZURE_OPENAI_DEPLOYMENT", "")
        self.temperature = float(os.getenv("AZURE_OPENAI_TEMPERATURE", "0.1"))
        self.max_tokens = int(os.getenv("AZURE_OPENAI_MAX_TOKENS", "800"))
        self._client = None
        if self.endpoint and self.api_key and self.deployment and AsyncAzureOpenAI is not None:
            self._client = AsyncAzureOpenAI(
                azure_endpoint=self.endpoint,
                api_key=self.api_key,
                api_version=self.api_version,
            )
        else:
            log.warning(
                "Azure OpenAI not fully configured (endpoint/key/deployment) — "
                "using offline deterministic LLM stub. Set AZURE_OPENAI_* env "
                "vars to use the real model."
            )

    @property
    def model_name(self) -> str:
        return self.deployment or "offline-stub"

    async def evaluate(
        self,
        *,
        system_prompt: str,
        evidence_context: str,
        requirement_id: int,
        agent_name: str,
        prompt_version: str,
        session_id: str,
    ) -> AgentVerdict:
        started = time.monotonic()
        if self._client is not None:
            data = await self._call_azure(system_prompt, evidence_context, requirement_id)
        else:
            data = self._call_offline_stub(evidence_context, requirement_id)

        data.setdefault("requirement_id", requirement_id)
        data.setdefault("agent_name", agent_name)
        data.setdefault("model_name", self.model_name)
        data.setdefault("prompt_version", prompt_version)

        try:
            verdict = AgentVerdict(**data)
        except ValidationError as exc:
            log.warning("Schema validation failed for req %s (%s); retrying once: %s",
                        requirement_id, agent_name, exc)
            if self._client is not None:
                data = await self._call_azure(
                    system_prompt, evidence_context, requirement_id,
                    correction_hint=str(exc),
                )
            else:
                data = self._call_offline_stub(evidence_context, requirement_id)
            data.setdefault("requirement_id", requirement_id)
            data.setdefault("agent_name", agent_name)
            data.setdefault("model_name", self.model_name)
            data.setdefault("prompt_version", prompt_version)
            verdict = AgentVerdict(**data)  # let this raise if still invalid

        latency_ms = int((time.monotonic() - started) * 1000)
        log.info(
            "llm_call session=%s req=%s agent=%s model=%s latency_ms=%d mock=%s",
            session_id, requirement_id, agent_name, self.model_name, latency_ms,
            self._client is None,
        )
        return verdict

    async def _call_azure(
        self, system_prompt: str, evidence_context: str, requirement_id: int,
        correction_hint: Optional[str] = None,
    ) -> dict[str, Any]:
        schema_hint = (
            "Respond ONLY with a JSON object with keys: "
            "compliance_status (one of 'Y','N','Partial','N/A'), "
            "rationale (string), evidence_citations (array of strings), "
            "gaps (array of strings), confidence (number 0-1)."
        )
        user_msg = f"{schema_hint}\n\nEvidence context:\n{evidence_context}"
        if correction_hint:
            user_msg += f"\n\nYour previous response was invalid: {correction_hint}\nFix it."
        try:
            resp = await self._client.chat.completions.create(  # type: ignore[union-attr]
                model=self.deployment,
                temperature=self.temperature,
                max_tokens=self.max_tokens,
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_msg},
                ],
            )
            content = resp.choices[0].message.content or "{}"
            return json.loads(content)
        except Exception as exc:
            log.error("Azure OpenAI call failed for req %s: %s", requirement_id, exc)
            return {
                "compliance_status": ComplianceStatus.PARTIAL.value,
                "rationale": f"LLM call failed ({exc}); evidence unavailable for automated review.",
                "evidence_citations": [],
                "gaps": ["LLM call failed — see server logs for details"],
                "confidence": 0.0,
            }

    @staticmethod
    def _call_offline_stub(evidence_context: str, requirement_id: int) -> dict[str, Any]:
        """Deterministic, dependency-free stand-in for the LLM so the whole
        pipeline is exercisable offline. Heuristic only — never use in
        production; it exists purely so `demo` mode works with zero infra."""
        lower = evidence_context.lower()
        no_evidence = (not evidence_context.strip()) or "unavailable" in lower or "failed" in lower or "no/invalid" in lower
        citation_matches = re.findall(r"\b(jira|gitlab|datadog|doc|confluence|iam):[\w./%-]+", evidence_context)
        citations = list(dict.fromkeys(citation_matches))[:3]

        if no_evidence:
            return {
                "compliance_status": ComplianceStatus.PARTIAL.value,
                "rationale": "No usable evidence was supplied or retrievable for this "
                             "requirement; cannot confirm compliance from available context.",
                "evidence_citations": [],
                "gaps": ["No evidence retrieved — connector unavailable or reference missing"],
                "confidence": 0.3,
            }
        return {
            "compliance_status": ComplianceStatus.YES.value,
            "rationale": (
                f"[offline-stub] Evidence context for requirement {requirement_id} contains "
                f"{len(evidence_context)} characters referencing "
                f"{', '.join(citations) if citations else 'the supplied sources'}, which "
                "appears to address the requirement. Replace this stub with a live Azure "
                "OpenAI deployment for real evaluation."
            ),
            "evidence_citations": citations,
            "gaps": [],
            "confidence": 0.6,
        }


LLM = AzureOpenAIWrapper()


# ===========================================================================
# Phase 8 — Guardrails
# ===========================================================================

CONFIDENCE_THRESHOLD = float(os.getenv("CONFIDENCE_THRESHOLD", "0.7"))


def verify_citations_grounded(verdict: AgentVerdict, context: str) -> AgentVerdict:
    """Programmatically confirm every citation exists in the evidence
    context supplied to that call; downgrade ungrounded 'Y' verdicts."""
    ungrounded = [c for c in verdict.evidence_citations if c and c not in context]
    if ungrounded:
        verdict.gaps = list(verdict.gaps) + [f"Ungrounded citation removed: {c}" for c in ungrounded]
        verdict.evidence_citations = [c for c in verdict.evidence_citations if c not in ungrounded]
        if verdict.compliance_status == ComplianceStatus.YES and not verdict.evidence_citations:
            verdict.compliance_status = ComplianceStatus.PARTIAL
            verdict.confidence = min(verdict.confidence, 0.5)
    return verdict


def needs_human_review(verdict: AgentVerdict) -> bool:
    """Confidence gating (Phase 8) + Requirement #10 self-application:
    Partial/N verdicts and anything under threshold are never auto-published."""
    return (
        verdict.confidence < CONFIDENCE_THRESHOLD
        or verdict.compliance_status in (ComplianceStatus.PARTIAL, ComplianceStatus.NO)
    )


def apply_guardrails(verdict: AgentVerdict, context: str) -> AgentVerdict:
    verdict = verify_citations_grounded(verdict, context)
    if not content_safety_scan(verdict.rationale):
        verdict.rationale = "[content redacted by safety scan]"
    verdict.flagged_for_human_review = needs_human_review(verdict)
    return verdict


# ===========================================================================
# Phase 1 — Prompt templates (one per agent type; versioned)
# ===========================================================================

PROMPT_VERSION = "v1.0"

AGENT_SYSTEM_PROMPTS: dict[str, str] = {
    "log_evidence": (
        "You are the Log Evidence Agent for an internal AI-audit tool. Your only job is to "
        "check whether the supplied log evidence demonstrates that the system's audit logs "
        "capture: inputs, outputs, prompts, timestamps, session metadata, model info, and "
        "source references. Only cite evidence present in the provided context (prefix "
        "'datadog:'); if any required field is missing or the log is unavailable, respond "
        "'Partial' or 'N' with the specific missing fields listed in `gaps` — never guess."
    ),
    "document": (
        "You are the Document Agent for an internal AI-audit tool. Your job is to check "
        "whether the supplied document/Confluence/code evidence satisfies the specific "
        "requirement text given to you. Only cite evidence present in the provided context "
        "(prefixes 'doc:'/'confluence:'/'gitlab:'); if evidence is incomplete or missing, "
        "respond 'Partial' with named gaps rather than rounding up to 'Y'."
    ),
    "compliance_registry": (
        "You are the Compliance Registry Agent. Your job is to verify that supplied "
        "governance approval identifiers (PRISM / AI Governance / BCIQ / ISS) are present "
        "in the evidence context and appear valid (non-empty, correctly labeled). Only cite "
        "evidence actually present in context; flag any missing approval type as a gap."
    ),
    "jira_gitlab": (
        "You are the Jira/GitLab Agent. Your job is to cross-reference Jira stories/ClearPath "
        "IDs with GitLab commits/MRs/releases/config-diffs to confirm the specific requirement "
        "text given to you (e.g., SDLC change tracking, feedback-to-change traceability, or "
        "kill-switch implementation & test evidence). Only cite evidence present in context "
        "(prefixes 'jira:'/'gitlab:'); if the trace is incomplete, respond 'Partial' with gaps."
    ),
    "access": (
        "You are the Access Agent. Your job is to answer identity/access-management questions "
        "(EU-user presence, service-account existence, service-account ownership/review "
        "process) strictly from the supplied evidence context (prefix 'iam:', which may be a "
        "manual submitter answer if no IAM API is configured). If the context is a manual "
        "answer, treat it as authoritative but note the lack of IAM-API verification as a gap."
    ),
}


def render_prompt(agent_name: str, requirement_id: int) -> str:
    req = REQUIREMENTS.get(requirement_id, {})
    base = AGENT_SYSTEM_PROMPTS.get(agent_name, "You are an audit evaluation agent.")
    return (
        f"{base}\n\n"
        f"Requirement #{requirement_id} ({req.get('category', 'Unknown category')}): "
        f"{req.get('text', 'No requirement text found in config.')}\n\n"
        f"Only answer using the evidence context you are given in the next message. "
        f"If evidence is incomplete, respond 'Partial' with an explicit `gaps` list."
    )


# ===========================================================================
# Phase 6 — Agents
# ===========================================================================

class BaseAgent(ABC):
    agent_name: str

    def __init__(self, llm: AzureOpenAIWrapper = LLM):
        self.llm = llm

    @abstractmethod
    async def gather_evidence(self, bundle: EvidenceBundle) -> tuple[str, list[str]]:
        """Call this agent's connectors and return (context_text, citation_ids)."""

    async def evaluate(self, bundle: EvidenceBundle, requirement_id: int) -> AgentVerdict:
        context, _citations = await self.gather_evidence(bundle)
        prompt = render_prompt(self.agent_name, requirement_id)
        verdict = await self.llm.evaluate(
            system_prompt=prompt,
            evidence_context=context,
            requirement_id=requirement_id,
            agent_name=self.agent_name,
            prompt_version=PROMPT_VERSION,
            session_id=bundle.session_id,
        )
        return apply_guardrails(verdict, context)

    @staticmethod
    def _join(results: list[ConnectorResult]) -> str:
        parts = []
        for r in results:
            if r.ok:
                parts.append(f"[{r.citation or r.source}] {r.content}")
            else:
                parts.append(f"[{r.source}:unavailable] {r.error}")
        return "\n\n".join(parts)


class LogEvidenceAgent(BaseAgent):
    agent_name = "log_evidence"

    async def gather_evidence(self, bundle: EvidenceBundle) -> tuple[str, list[str]]:
        results = [await CONNECTORS["datadog"].fetch(bundle.datadog_link)]
        if bundle.screenshot_refs:
            for ref in bundle.screenshot_refs:
                results.append(ConnectorResult(source="screenshot", ref=ref, ok=True,
                                                content=f"[screenshot on file: {ref}]",
                                                citation=f"screenshot:{ref}"))
        return self._join(results), [r.citation for r in results if r.citation]


class DocumentAgent(BaseAgent):
    agent_name = "document"

    async def gather_evidence(self, bundle: EvidenceBundle) -> tuple[str, list[str]]:
        results: list[ConnectorResult] = []
        for ref in bundle.document_refs:
            results.append(await CONNECTORS["doc_store"].fetch(ref))
        if bundle.gitlab_link:
            results.append(await CONNECTORS["gitlab"].fetch(bundle.gitlab_link))
        if not results and bundle.user_input:
            results.append(ConnectorResult(source="user_input", ok=True,
                                            content=bundle.user_input, citation="user_input"))
        if not results:
            results.append(ConnectorResult(source="doc_store", ok=False, content="",
                                            error="No document_refs or GitLab link supplied"))
        return self._join(results), [r.citation for r in results if r.citation]


class ComplianceRegistryAgent(BaseAgent):
    agent_name = "compliance_registry"

    async def gather_evidence(self, bundle: EvidenceBundle) -> tuple[str, list[str]]:
        results: list[ConnectorResult] = []
        if bundle.user_input:
            results.append(ConnectorResult(source="user_input", ok=True,
                                            content=bundle.user_input, citation="user_input"))
        for ref in bundle.document_refs:
            results.append(await CONNECTORS["doc_store"].fetch(ref))
        if not results:
            results.append(ConnectorResult(source="user_input", ok=False, content="",
                                            error="No governance IDs supplied via user_input or document"))
        return self._join(results), [r.citation for r in results if r.citation]


class JiraGitLabAgent(BaseAgent):
    agent_name = "jira_gitlab"

    async def gather_evidence(self, bundle: EvidenceBundle) -> tuple[str, list[str]]:
        results = [
            await CONNECTORS["jira"].fetch(bundle.jira_link),
            await CONNECTORS["gitlab"].fetch(bundle.gitlab_link),
        ]
        if bundle.screenshot_refs:
            for ref in bundle.screenshot_refs:
                results.append(ConnectorResult(source="screenshot", ref=ref, ok=True,
                                                content=f"[screenshot on file: {ref}]",
                                                citation=f"screenshot:{ref}"))
        return self._join(results), [r.citation for r in results if r.citation]


class AccessAgent(BaseAgent):
    agent_name = "access"

    async def gather_evidence(self, bundle: EvidenceBundle) -> tuple[str, list[str]]:
        results = [await CONNECTORS["iam"].fetch(bundle.user_input)]
        for ref in bundle.document_refs:
            results.append(await CONNECTORS["doc_store"].fetch(ref))
        return self._join(results), [r.citation for r in results if r.citation]


AGENT_REGISTRY: dict[str, type[BaseAgent]] = {
    "log_evidence": LogEvidenceAgent,
    "document": DocumentAgent,
    "compliance_registry": ComplianceRegistryAgent,
    "jira_gitlab": JiraGitLabAgent,
    "access": AccessAgent,
}


# ===========================================================================
# Phase 7 — Orchestrator & routing (stateless: returns results, stores nothing)
# ===========================================================================

AGENT_TIMEOUT_SECONDS = float(os.getenv("AGENT_TIMEOUT_SECONDS", "30"))

# Optional hook: if you later want to persist/stream verdicts as they
# complete (Phase 2's "persist as it completes" idea) without threading
# storage code through the agents/orchestrator, register a callback here.
# It receives (session_id, AgentVerdict) and is fired right after each
# verdict is computed. Left as a no-op by default — nothing is stored.
OnVerdictHook = Callable[[str, AgentVerdict], Awaitable[None]]


def resolve_agent_for_requirement(requirement_id: int) -> BaseAgent:
    entry = REQUIREMENTS.get(requirement_id)
    if not entry:
        raise KeyError(f"Unknown requirement_id {requirement_id} — not in routing config")
    agent_cls = AGENT_REGISTRY.get(entry["agent"])
    if not agent_cls:
        raise KeyError(f"No agent registered for '{entry['agent']}' (requirement {requirement_id})")
    return agent_cls()


async def _evaluate_one(
    bundle: EvidenceBundle, requirement_id: int, on_verdict: Optional[OnVerdictHook],
) -> AgentVerdict:
    try:
        agent = resolve_agent_for_requirement(requirement_id)
        verdict = await asyncio.wait_for(
            agent.evaluate(bundle, requirement_id), timeout=AGENT_TIMEOUT_SECONDS
        )
    except asyncio.TimeoutError:
        verdict = AgentVerdict(
            requirement_id=requirement_id, agent_name="orchestrator",
            compliance_status=ComplianceStatus.PARTIAL,
            rationale="Agent timed out before producing a verdict.",
            evidence_citations=[], gaps=["Agent timeout — evidence unavailable"],
            confidence=0.0, model_name=LLM.model_name, prompt_version=PROMPT_VERSION,
            flagged_for_human_review=True,
        )
    except Exception as exc:  # never let one bad requirement kill the whole run
        log.exception("Agent failed for requirement %s", requirement_id)
        verdict = AgentVerdict(
            requirement_id=requirement_id, agent_name="orchestrator",
            compliance_status=ComplianceStatus.PARTIAL,
            rationale=f"Agent raised an unexpected error: {exc}",
            evidence_citations=[], gaps=[f"Unhandled error: {exc}"],
            confidence=0.0, model_name=LLM.model_name, prompt_version=PROMPT_VERSION,
            flagged_for_human_review=True,
        )
    if on_verdict is not None:
        await on_verdict(bundle.session_id, verdict)
    return verdict


async def route_and_evaluate(
    bundle: EvidenceBundle, on_verdict: Optional[OnVerdictHook] = None,
) -> list[AgentVerdict]:
    """Runs every requested requirement concurrently and returns the
    resulting verdicts. Nothing is read from or written to any store —
    the EvidenceBundle in, list[AgentVerdict] out, is the entire contract."""
    tasks = [_evaluate_one(bundle, req_id, on_verdict) for req_id in bundle.requirement_ids]
    return await asyncio.gather(*tasks)


# ===========================================================================
# Phase 9 — Aggregator (built purely from the in-memory verdict list)
# ===========================================================================

def build_audit_report(session_id: str, verdicts: list[AgentVerdict]) -> AuditRunReport:
    if not verdicts:
        raise ValueError("Cannot build a report from an empty verdict list")
    flagged_ids = [v.requirement_id for v in verdicts if v.flagged_for_human_review]
    yes_count = sum(1 for v in verdicts if v.compliance_status == ComplianceStatus.YES)
    readiness = round(100.0 * yes_count / len(verdicts), 1)
    return AuditRunReport(
        session_id=session_id,
        verdicts=verdicts,
        overall_readiness_pct=readiness,
        flagged_for_human_review=flagged_ids,
    )


def apply_review(review: ReviewRequest) -> AgentVerdict:
    """Stateless review/override transform (Phase 10's decision logic,
    without a persisted audit trail). Takes the verdict the caller already
    has and returns the updated one; storing it is the caller's job."""
    verdict = review.verdict.model_copy(deep=True)
    if review.action == ReviewAction.APPROVE:
        verdict.flagged_for_human_review = False
        verdict.rationale = f"{verdict.rationale}\n[Approved by {review.reviewer}: {review.rationale}]"
    else:  # OVERRIDE
        if review.override_status is not None:
            verdict.compliance_status = review.override_status
        verdict.flagged_for_human_review = False
        verdict.rationale = f"[Reviewer override by {review.reviewer}] {review.rationale}"
    return verdict


# ===========================================================================
# FastAPI app — stateless: request payload in, result out, nothing stored
# ===========================================================================

app = None
if FastAPI is not None:
    app = FastAPI(
        title="AI Audit Evaluation Agents",
        description="Stateless multi-agent evaluator: send an EvidenceBundle, "
                     "get an AuditRunReport back. Nothing is persisted server-side.",
        version=PROMPT_VERSION,
    )

    @app.get("/health")
    async def health() -> dict[str, str]:
        return {"status": "ok", "llm_mode": "azure" if LLM._client else "offline-stub",
                "persistence": "none"}

    @app.post("/audit/evaluate", response_model=AuditRunReport)
    async def audit_evaluate(bundle: EvidenceBundle) -> AuditRunReport:
        """Runs the full audit check for the requirement_ids in the payload
        and returns the report directly. Nothing about this request is
        stored anywhere once the response is sent."""
        try:
            verdicts = await route_and_evaluate(bundle)
            return build_audit_report(bundle.session_id, verdicts)
        except KeyError as exc:
            raise HTTPException(status_code=400, detail=str(exc))

    @app.post("/audit/review", response_model=AgentVerdict)
    async def audit_review(review: ReviewRequest) -> AgentVerdict:
        """Stateless approve/override: send back the verdict you got from
        /audit/evaluate plus the reviewer's decision; get the updated
        verdict back. Persisting it is left to the caller."""
        return apply_review(review)

    @app.get("/audit/config/requirements")
    async def get_requirements_config() -> dict[int, dict[str, Any]]:
        return REQUIREMENTS


# ===========================================================================
# CLI — offline demo + server launcher
# ===========================================================================

async def run_demo() -> None:
    print("=" * 78)
    print("AI Audit Agents — offline demo (mocked connectors" +
          (", offline LLM stub" if LLM._client is None else ", LIVE Azure OpenAI") + ")")
    print("Stateless mode: nothing is persisted; results exist only for this run.")
    print("=" * 78)

    bundle = EvidenceBundle(
        requirement_ids=list(REQUIREMENTS.keys()),
        user_input=(
            "PRISM-2024-0091 approved on 2024-11-03. EU users: yes, ~120 users in "
            "Germany and France. Service account svc-ai-audit-bot exists, owned by "
            "Platform Engineering, reviewed quarterly by the IAM team."
        ),
        document_refs=[],  # left empty on purpose to also exercise the "Partial" path
        screenshot_refs=["s3://demo-bucket/logging-config-screenshot.png"],
        jira_link="https://example.atlassian.net/browse/AIAUDIT-101",
        gitlab_link="https://gitlab.example.com/platform/ai-audit/-/merge_requests/42",
        datadog_link="https://app.datadoghq.com/logs?query=service:ai-audit",
        submitted_by="demo-user",
    )

    verdicts = await route_and_evaluate(bundle)
    report = build_audit_report(bundle.session_id, verdicts)

    for v in sorted(verdicts, key=lambda x: x.requirement_id):
        req = REQUIREMENTS.get(v.requirement_id, {})
        flag = " [FLAGGED FOR HUMAN REVIEW]" if v.flagged_for_human_review else ""
        print(f"\nReq #{v.requirement_id} ({req.get('category')}) — {v.agent_name}{flag}")
        print(f"  Status: {v.compliance_status.value}   Confidence: {v.confidence:.2f}")
        print(f"  Rationale: {v.rationale[:200]}")
        if v.gaps:
            print(f"  Gaps: {v.gaps}")
        if v.evidence_citations:
            print(f"  Citations: {v.evidence_citations}")

    print("\n" + "-" * 78)
    print(f"Session: {report.session_id}  (not stored — exists only in this response)")
    print(f"Overall readiness: {report.overall_readiness_pct}%")
    print(f"Flagged for human review: {report.flagged_for_human_review}")
    print("-" * 78)
    print("\nDemo complete. Try the API with:")
    print("  python ai_audit_agents.py serve")
    print("  curl -X POST localhost:8000/audit/evaluate -H 'content-type: application/json' \\")
    print("       -d '{\"requirement_ids\":[1,11],\"submitted_by\":\"me\"}'")


def main() -> None:
    parser = argparse.ArgumentParser(description="AI Audit Evaluation Agents (stateless)")
    sub = parser.add_subparsers(dest="command")
    sub.add_parser("demo", help="Run an offline, end-to-end demo against all 13 requirements")
    serve_p = sub.add_parser("serve", help="Run the FastAPI app with uvicorn")
    serve_p.add_argument("--host", default="0.0.0.0")
    serve_p.add_argument("--port", type=int, default=8000)
    serve_p.add_argument("--reload", action="store_true")
    args = parser.parse_args()

    if args.command == "serve":
        if app is None:
            sys.exit("FastAPI is not installed. `pip install fastapi uvicorn` first.")
        import uvicorn
        uvicorn.run("ai_audit_agents:app", host=args.host, port=args.port, reload=args.reload)
    else:
        asyncio.run(run_demo())


if __name__ == "__main__":
    main()
